# Generated by Django 3.2.12 on 2022-03-07 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anganwadi_app', '0003_district_location_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districtofficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, null=True)),
                ('housename', models.CharField(max_length=100, null=True)),
                ('emil', models.CharField(max_length=100, null=True)),
                ('id_proof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('Image', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('street', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('confirmpassword', models.CharField(max_length=100, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location')),
                ('prooftype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.prooftype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
