# Generated by Django 3.2.12 on 2022-03-08 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anganwadi_app', '0004_districtofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='anganawadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100, null=True)),
                ('a_pic', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('a_proof', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('a_licenseno', models.CharField(max_length=100, null=True)),
                ('a_contact', models.CharField(max_length=100, null=True)),
                ('a_email', models.CharField(max_length=100, null=True)),
                ('a_username', models.CharField(max_length=100, null=True)),
                ('a_password', models.CharField(max_length=100, null=True)),
                ('a_status', models.CharField(max_length=100, null=True)),
                ('dofficer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
