# Generated by Django 3.2.12 on 2022-03-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0006_anganawadi_a_confirmpsw'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_pic', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('food_name', models.CharField(max_length=100, null=True)),
                ('food_description', models.CharField(max_length=200, null=True)),
                ('dofficer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('foodtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.foodtype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pwomenfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_pic', models.ImageField(null=True, upload_to='', verbose_name='images/')),
                ('pfood_amt', models.CharField(max_length=100, null=True)),
                ('pfood_duration', models.CharField(max_length=100, null=True)),
                ('pfood_name', models.CharField(max_length=100, null=True)),
                ('food_description', models.CharField(max_length=200, null=True)),
                ('dofficer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.districtofficer')),
                ('foodtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.foodtype')),
            ],
        ),
    ]
