# Generated by Django 3.2.12 on 2022-03-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0008_tbl_userfood_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userfoodservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_qty', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(max_length=100, null=True)),
                ('end_date', models.DateField(max_length=100, null=True)),
                ('active_status', models.CharField(max_length=100, null=True)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('anganwadi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
            ],
        ),
    ]
