# Generated by Django 3.2.12 on 2022-03-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0011_tbl_foodstockrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_foodstockrequest',
            old_name='a_id',
            new_name='user',
        ),
    ]
