# Generated by Django 3.2.12 on 2022-03-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0014_tbl_pwomenfoodservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pwomenfoodservice',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomenfood'),
        ),
    ]
