# Generated by Django 3.2.12 on 2022-03-10 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anganwadi_app', '0015_alter_tbl_pwomenfoodservice_food_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_totalpfoodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pfood_totalStock', models.IntegerField(max_length=100, null=True)),
                ('Pfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_pfoodstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pfood_stock', models.IntegerField(max_length=100, null=True)),
                ('Pfoodstock_date', models.DateField(max_length=100, null=True)),
                ('Pfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
