# Generated by Django 3.2.12 on 2022-03-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0016_tbl_pfoodstock_tbl_totalpfoodstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_pfoodstock',
            old_name='Pfood_id',
            new_name='pfood_id',
        ),
        migrations.RenameField(
            model_name='tbl_pfoodstock',
            old_name='Pfood_stock',
            new_name='pfood_stock',
        ),
        migrations.RenameField(
            model_name='tbl_pfoodstock',
            old_name='Pfoodstock_date',
            new_name='pfoodstock_date',
        ),
        migrations.RenameField(
            model_name='tbl_totalpfoodstock',
            old_name='Pfood_id',
            new_name='pfood_id',
        ),
        migrations.RenameField(
            model_name='tbl_totalpfoodstock',
            old_name='Pfood_totalStock',
            new_name='pfood_totalStock',
        ),
    ]
