# Generated by Django 3.2.12 on 2022-03-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0020_auto_20220310_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_child',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi'),
        ),
        migrations.AlterField(
            model_name='tbl_child',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.user'),
        ),
    ]
