# Generated by Django 3.2.12 on 2022-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0021_auto_20220310_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_child',
            name='birthcertificate',
            field=models.ImageField(null=True, upload_to='', verbose_name='images/'),
        ),
    ]
