# Generated by Django 3.2.12 on 2022-03-10 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anganwadi_app', '0022_alter_tbl_child_birthcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_child',
            name='child_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
