# Generated by Django 3.2.12 on 2022-03-10 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anganwadi_app', '0023_alter_tbl_child_child_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_healthtips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips_title', models.CharField(max_length=100, null=True)),
                ('tips_description', models.CharField(max_length=300, null=True)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
