# Generated by Django 3.2.12 on 2022-03-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0024_tbl_healthtips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_healthtips',
            name='a_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi'),
        ),
    ]
