# Generated by Django 3.2.12 on 2022-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0026_tbl_pwomens_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_pwomens',
            name='pwomen_pincode',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
