# Generated by Django 3.2.12 on 2022-03-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0027_tbl_pwomens_pwomen_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_pwomens',
            name='pwomen_age',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
