# Generated by Django 3.2.12 on 2022-03-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0028_tbl_pwomens_pwomen_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pwomens',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location'),
        ),
        migrations.AlterField(
            model_name='tbl_pwomens',
            name='place_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='place_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.place'),
        ),
    ]
