# Generated by Django 3.2.12 on 2022-03-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0029_auto_20220311_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.DateField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=300, null=True)),
                ('pwomen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomens')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300, null=True)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=300, null=True)),
                ('complaint_status', models.CharField(max_length=300, null=True)),
                ('complainttype_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.location')),
                ('pwomen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomens')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_user')),
            ],
        ),
    ]
