# Generated by Django 3.2.12 on 2022-03-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0030_tbl_complaint_tbl_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complainttype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.complainttype'),
        ),
    ]
