# Generated by Django 3.2.12 on 2022-03-14 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anganwadi_app', '0032_tbl_pwomens_pwomen_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_foodbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfoodbooking_date', models.DateField(auto_now_add=True)),
                ('pfoodbooking_status', models.CharField(max_length=300, null=True)),
                ('pwomen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pwomenfoodservice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfoodservice')),
            ],
        ),
    ]
