# Generated by Django 3.2.12 on 2022-03-14 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anganwadi_app', '0033_tbl_foodbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_foodbooking',
            old_name='pfoodbooking_date',
            new_name='foodbooking_date',
        ),
        migrations.RenameField(
            model_name='tbl_foodbooking',
            old_name='pfoodbooking_status',
            new_name='foodbooking_status',
        ),
        migrations.RenameField(
            model_name='tbl_foodbooking',
            old_name='pwomen_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='tbl_foodbooking',
            old_name='pwomenfoodservice_id',
            new_name='userfoodservice_id',
        ),
        migrations.CreateModel(
            name='tbl_pfoodbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfoodbooking_date', models.DateField(auto_now_add=True)),
                ('pfoodbooking_status', models.CharField(max_length=300, null=True)),
                ('pwomen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pwomenfoodservice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfoodservice')),
            ],
        ),
    ]
