# Generated by Django 3.2.12 on 2022-03-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0034_auto_20220314_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_pfoodbooking',
            name='pwomenfoodservice_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_pwomenfoodservice'),
        ),
    ]
