# Generated by Django 3.2.12 on 2022-03-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0036_auto_20220317_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_foodbooking',
            old_name='anganwadi',
            new_name='Anganwadi',
        ),
        migrations.RenameField(
            model_name='tbl_pfoodbooking',
            old_name='anganwadi',
            new_name='Anganwadi',
        ),
    ]
