# Generated by Django 3.2.12 on 2022-03-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0037_auto_20220317_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='usertype',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback',
            name='usertype',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
