# Generated by Django 3.2.12 on 2022-03-18 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0038_auto_20220318_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_foodstockrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi'),
        ),
        migrations.AlterField(
            model_name='tbl_pfoodstockrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.anganawadi'),
        ),
    ]
