# Generated by Django 3.2.12 on 2022-03-19 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anganwadi_app', '0041_auto_20220319_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_childfoodstock',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood'),
        ),
        migrations.AlterField(
            model_name='tbl_childfoodstockrequest',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood'),
        ),
        migrations.AlterField(
            model_name='tbl_totalchildfoodstock',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anganwadi_app.tbl_userfood'),
        ),
    ]
